# Generated by Django 3.2.9 on 2022-06-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heyurl', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
